algoritmo "Tabuada com a função for"
// Função : tabuada com a função para/for
// Autor : Gabriel Toledo
// Data : 04/04/2023
// Seção de Declarações
var
   num, i, conta:inteiro
inicio
      escreva("Digite o número para calcular a tabuada: ")
      leia(num)
      para i de 1 ate 10 faca
           conta:=num*i
           escreval(num," X ",i," = ",conta)
      fimpara
fimalgoritmo
